# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-10-09 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20191010_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assembly',
            old_name='assembly_line_no',
            new_name='assemblyLineNO',
        ),
        migrations.RenameField(
            model_name='assembly',
            old_name='bin_id',
            new_name='binId',
        ),
        migrations.RenameField(
            model_name='assembly',
            old_name='bin_name',
            new_name='binName',
        ),
        migrations.AlterField(
            model_name='assembly',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
