# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-10-09 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20191010_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembly',
            name='assemblyLineNO',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='binId',
            field=models.CharField(max_length=20),
        ),
    ]
